### ISSUE TITLE
Enigmail for Interlink Mail

### ISSUE THREAD

**Issue by pbrunschwig** [binaryoutcast/binoc-central#103]
I'm the maintainer of the Enigmail add-on for Thunderbird. I'm planning to create an official release of Enigmail for Interlink. I'm not sure if a ticket is the right place to discuss this, but I could not find a better way to contact you guys. 

I have a few questions concerning the integration of Enigmail in Interlink:

1. Would you be willing to list Enigmail on the Addons-page of Interlink, once the release is ready? If yes, who maintains that page - can I upload/publish new versions on my own?

2. I noticed that the platform version of Interlink is currently 4.6.0, while the App-version is 52.9.xxxx. What is the 4.6.0 version, when does it change and what implications are related to changed version numbers? I'm asking because that complicates the code for me a bit - I sometimes need to handle certain things differently depending on the application version; and so far I used the platform version for that.

3. I made a few improvements to APIs in Thunderbird 68 that make it easier to integrate Enigmail. Would you be willing to apply these improvements in future versions of Interlink? I'm talking about the following bugs:
https://bugzilla.mozilla.org/show_bug.cgi?id=1414518
https://bugzilla.mozilla.org/show_bug.cgi?id=1486217
https://bugzilla.mozilla.org/show_bug.cgi?id=1531806

**Comment by wolfbeast** [comment]
Hi Patrick,

I was asked to look into this (although I may not be around much for the next 2 weeks) since I'm an active user of Enigmail on Interlink (using 1.9.9 since 2.* had proven to be problematic) and can work with you to work something out.

To answer your questions:

1. Our add-ons site is multi-application aware, so once it is release-ready it could be uploaded and distributed through there through the self-serve developer panel. You'd have full access to update extensions yourself.
2. It seems you aren't fully aware of the structure here. Unlike what Mozilla has done, we have returned to separating the platform (UXP) from the applications (Pale Moon, Basilisk, Interlink, etc.). The platform has its own version number, and in our case you can't use it as a replacement for application version since they are separate and distinct. The mailnews core is part of UXP.
3. The API changes look sane to me although I'm a bit worried about 1486217 breaking other extensions or messing up internal S/MIME handling with certificates if not done carefully. For those to land you'll have to open separate issues on MoonchildProductions/UXP as they are implemented in the mailnews core AFAICT -- Any accompanying changes will have to be made in the application repos (and this, especially the second, would also affect the frontend of Hyperbola's applications that do mail handling, so ping @g4jc here). By the way, we do like to keep the practice of bumping the UUID of XPIDL interfaces when they change.

In general for the extension side of things, XUL overlay extensions work many times better on UXP than fragile bootstrapping, which I think has been part of the incompatibility issues with 2.* for me, so I think the preference here would be strongly for fixing up 1.9.9 which already works as-is with any improvements you've made over swapping it out with a bootstrapped kind of extension.

**Comment by pbrunschwig** [comment]
Thanks for your answers! I'm actually working on the latest release version, which is 2.1.7. Enigmail 1.9.9 is about 3 years old, and not maintained anymore. There are several known severe security issues in Enigmail 1.9.9, and I implemented quite many new features like Autocrypt since then. Backporting all of this the the 1.9.9 branch is almost impossible - there were too many severe changes in the code since then, and many more to come for future versions of Enigmail.

You're the first to tell me that the bootstrapping mechanism caused problems. From the feedback and bug reports I got from users in the past two years, I cannot confirm this at all - with one exception (you cannot place the Enigmail icons in a custom toolbar, they need to be in the primary toolbar).

I might look into going back to a non-bootstrapped add-on for Interlink (that should not be too complicated). But as Enigmail also works on Postbox, I intend to support both Postbox and Interlink from the same code base. As Postbox is working on porting their code to Thunderbird 68, I will have to keep the bootstrapped code somehow. 

In any case, I'll continue to make Enigmail 2.1.7 work properly on Interlink and then I'll get back to you. The API changes can be done separately - they're not urgent.

**Comment by wolfbeast** [comment]
> There are several known severe security issues in Enigmail 1.9.9, and I implemented quite many new features like Autocrypt since then. Backporting all of this the the 1.9.9 branch is almost impossible - there were too many severe changes in the code since then, and many more to come for future versions of Enigmail.

I understand. 

As for bootstrapping, in most cases it's simply a mess and while it can work, there have been quite a few reports of bootstrapped extensions doing unpredictable, hard-to-reproduce-by-others things, especially UI-wise, that are all solved by using the clear resource separation approach in overlays. Some extension maintainers in our corner have made it a point to convert bootstrapped to overlay while targeting Pale Moon, for example.

> I might look into going back to a non-bootstrapped add-on for Interlink (that should not be too complicated). 

 If you can reasonably do that, then that would be great. Does the Thunderbird 68 code base no longer support using non-bootstrapped? You might want to maintain a separate branch for bootstrapped/non-bootstrapped; ultimately the best approach is to target your targets specifically instead of trying to compromise for an amalgamation, I think.

> The API changes can be done separately - they're not urgent.

That's good. they need a bit more coordination.

**Comment by pbrunschwig** [comment]
I have completed Enigmail 2.1.7 for Interlink Mail & News (the latest stable version of Enigmail) . It's a classical add-on, but overlaying is implemented identically to a bootstrapped add-on, using the some overlay library as Thunderbird 68. The changes I'd have to make are not compatible with the bootstrapped addon that I need for TB 68 and Postbox.

The XPI can be found here: https://enigmail.net/download/release/2.1/enigmail-2.1.7.1-il.xpi

How do we proceed now?

**Comment by wolfbeast** [comment]
... if you're going to use bootstrap methods anyway to build the UI components and overlay elements (instead of actually using a XUL overlay) in an overlay extension, then you may as well keep it bootstrap since it won't solve anything and will just be annoying to the user for requiring restarts while not actually relieving the bootstrap-caused issues. The whole point of asking for an overlay extension is so it can be natively overlaid with XUL and not ad hoc UI-injected. It's not like that would be a problem for the way Enigmail interacts, would it? I mean all the controls are pretty well set in where they go.
Sorry if there's something obvious aside from a bit of extra XML work needed that I'm missing as to why you want to keep using bootstrapping one way or another anyway, but please enlighten me in that case.

**Comment by pbrunschwig** [comment]
First, the Enigmail overlays are not that simple. The overlay files for the main mail window span across 700 lines of code, and the one for the message composition window is another 300 lines of code. Maintaining multiple versions thereof is not exactly trivial. In addition, the there are subtle but important differences in the timing of the "load" event on bootstrapped windows versus classical windows.

When we (some TB devs and I) developed what you call the "ad hoc UI-injected" mechanism, we basically re-implemented the XUL overlaying mechanism that was written in C++ with a JavaScript version that does exactly the same and behaves very similarly. All classical add-ons in TB 68 use that mechanism, and I have not heard of any problems with it.

There is one thing though that makes bootstrapped addons more fragile than non-bootstrapped, which is why I decided to go this way. If you disable the addon or install a new version, without restarting the mail client, then things become hairy. You have to make sure that everything is unloaded (all UI elements, but also all JavaScript code). That's quite complicated and error-prone, and sometimes just impossible. For example you can't de-register a custom mail filter handler. Thus, if you install an update, you can easily get something that is half-new and half-old, which is why I prefer a non-bootstrapped addon, that cannot have such pitfalls.

**Comment by wolfbeast** [comment]
I see, thanks for explaining!
What I don't understand though is, since you are already having the overlay files and we support the C++ XUL overlay implementation (that Mozilla decided to strip), and are in effect doing the _exact same thing_ through JavaScript, why you're not wanting to use our C++ implementation which is native to us. The overlays _themselves_ wouldn't need to change for that, IIUC, since the only thing different would be _how_ they are loaded in the windows (either through a manifest/C++ or through a JS-based injector) and not what they do...? If I misunderstand, please explain.

**Comment by wolfbeast** [comment]
While I wait for your reply to the above I'll spend some time checking the extension as it is now, see if I run into any issues with it.
Considering my setup I think it's a decent torture test representative of about the most heavy use you'll see. I'll report back in a few days on that.

**Comment by pbrunschwig** [comment]
The reason is that, as we are not _inside_ the XUL interpreter, some things work the same way, but the XUL elements need to be prepared differently. 

For example for loading CSS in regular XUL overlays you write this bit:
`<?xml-stylesheet href="chrome://enigmail/skin/enigmail.css" type="text/css"?>`

That doesn't work in the JavaScript overlay loader. Instead we use the HTML variant for loading CSS:
`<link rel="stylesheet" type="text/css" href="chrome://enigmail/skin/enigmail.css"/>`

Another difference is for declaring toolbar buttons.

**Comment by mattatobin** [comment]
So preprocess.. Last I checked, you had a subset of the Mozilla build system with a preprocessor.

```
// Somewhere conditional the value of a define like STYLESHEET_PREFIX

if TARGET_INTERLINK
  STYLESHEET_PREFIX=<?xml-stylesheet type="text/css"
  STYLESHEET_SUFFIX=?>
else
  STYLESHEET_PREFIX=<link rel="stylesheet"
  STYLESHEET_SUFFIX=/>
endif

// Then in your xul files
#expand __STYLESHEET_PREFIX__ href="chrome://enigmail/skin/enigmail.css" __STYLESHEET_SUFFIX__
```

**Comment by pbrunschwig** [comment]
Yes, I could preprocess. But it would need quite a few more subtle changes. Enigmail 2.1.x is my stable branch and I don't want to go that route for a version that should be stable. Not to speak of the testing effort - I'd have to test _everything_ on Thunderbird 68, Postbox and Interlink.

I will quite likely change this on my development branch (which will one day become version 3.0), but it's simply out of question for Enigmail 2.1.x.

**Comment by pbrunschwig** [comment]
I have given this some more thought, and I have an idea how to minimize the risk of incompatible changes. On of my biggest concerns is that the timing of the "load" event is different in bootstrapped mode vs. classical mode, which may lead to different behavior. My idea is to convert all overlays into classical ones, but to create a new dummy overlay that is loaded like in bootstrapped mode. The dummy overlay will cause the "load" event to be fired exactly like in bootstrapped mode.

I'll give this a try and let you know if it relieves my concerns.

**Comment by pbrunschwig** [comment]
Good news, my solution works, there were almost no changes needed to make Enigmail work in both "classical" and "bootstrap" style. I have created an updated version; this is now a truly classical addon, with all XUL elements loaded via the builtin XUL loader:
https://enigmail.net/download/release/2.1/enigmail-2.1.7.1-il-v2.xpi

**Comment by wolfbeast** [comment]
I've been testing the previous (pseudo-bootstrapped) version and it seems to be OK but there's a problem with the compose window. In it, there should be an indicator whether a mail is going to be sent signed and/or encrypted. The menu displays it, but the indicator (in the status bar) nor the message in the toolbar is present, which is essential for visually verifying the status of outgoing mail.

**Comment by wolfbeast** [comment]
PGP4Win 3.x also seems to be hopelessly broken. It doesn't recognize half the private keys I have. Aside from the fact that keyserver communication seems to be broken as well which has been reported already.

**Comment by pbrunschwig** [comment]
> I've been testing the previous (pseudo-bootstrapped) version and it seems to be OK but there's a problem with the compose window. In it, there should be an indicator whether a mail is going to be sent signed and/or encrypted. The menu displays it, but the indicator (in the status bar) nor the message in the toolbar is present, which is essential for visually verifying the status of outgoing mail.

There are no icons in the status bar anymore - I removed them long ago (I believe with Enigmail 2.0).

The toolbar buttons work perfectly fine for me (see attachment).

![image](https://user-images.githubusercontent.com/12988906/89102143-9a30c080-d406-11ea-825d-2ce7905eb4db.png)

**Comment by wolfbeast** [comment]
Well keep in mind that I'm coming from 1.9.9 here and moving to this version does not automatically replace the status bar icons (we do have a status bar for a reason in interlink...) with the toolbar icons so there's no indication or control after migrating.

**Comment by pbrunschwig** [comment]
Yes, but the toolbar icons are added by default (I still need to fix this for the classical XUL version).

**Comment by pbrunschwig** [comment]
Concerning gpg4win 3.x: try `gpg --list-secret-keys` from the command line. Are your private keys all available (I don't expect this).

Keyservers: whatever has been reported for Enigmail 1.9x. and 2.0.x  -- it's not valid for 2.1.x anymore. I implemented all keyserver functionality from scratch, and don't depend on gpg anymore for this. I would need to know more precisely what doesn't work (a debugging log file would be helpful).

**Comment by pbrunschwig** [comment]
My experience with keyservers is that 90% of all issues are caused by the keyservers. Many are not working properly. 

I recommend the following keyservers:
keyserver.ubuntu.com
pgp.mit.edu
keys.openpgp.org

**Comment by wolfbeast** [comment]
Ah might be because the main key server entry is the pool address for sks keyservers.

As for gpg3 and secret keys, no, it doesn't list the secret keys I'm looking for from the command-line either. gpg2 does.

**Comment by pbrunschwig** [comment]
Follow the suggestions in this support thread:
https://sourceforge.net/p/enigmail/forum/support/thread/71f5f6c4bf/

That should re-import your keys from gpg2.0 to gpg 2.2

**Comment by wolfbeast** [comment]
Thanks for the offtopic assist. Unfortunately it seems that there's something wrong and although I have more keys now, the most important ones (of course) are still broken. gpg 2.0.26 can read them, 2.2.19 cannot. I guess I'm stuck with creating a new key pair and getting it re-signed by people which is unlikely to happen anytime soon.

**Comment by pbrunschwig** [comment]
How old is your key? gpg 2.2 only supports OpenPGPv4 keys. Did you try to export from gpg2 and import in gpg2.2 via the command line?

```
gpg2 -o keys.asc -a --export-secret-keys
gpg2.2 --import keys.asc
```

**Comment by wolfbeast** [comment]
I'll try export/import. that's not really relevant here though. I'll figure something out.

What's more important is that I'm having issues with your v2. Trying to open the Key Management interface will sometimes load and sometimes not (it will open and immediately close). No errors reported in the error console.

**Comment by pbrunschwig** [comment]
Hmm, that's weird. It works fine on my side, and I have a huge set of keys. Do you try to open it _immediately_ after starting Interlink?

**Comment by pbrunschwig** [comment]
That's likely due to again hanging gpg processes. Kill all gpg processes and make sure that all lock files are removed in your GnuPGHOME directory.

**Comment by wolfbeast** [comment]
I'm sorry, but it seems all of this is due to gpg4win 3.
I went back to the 2.0 build and restored my keyring backup, and everything seems to be working.

**Comment by pbrunschwig** [comment]
That's great. This is a typical example for the blame I get about broken things that have nothing to do with Enigmail ...

How shall we proceed now? Is this now OK for you to host on the Interlink add-ons page?

**Comment by mattatobin** [comment]
Are you still using `gpg4win3`?

**Comment by pbrunschwig** [comment]
Yes we still use gpg4win3 - it's the only viable option on Windows.

The problems that @wolfbeast had with gpg4win v3 are related to his own setup. I believe that he still uses OpenPGP v3 keys, which are no longer supported by GnuPG 2.2 (part of gpg4win3). 

The issue with gpg4win2 (or better: GnuPG 2.0.x) is that it's not supported anymore. It has several known vulnerabilities and does not support ECC keys. I therefore strongly recommend to upgrade.

**Comment by wolfbeast** [comment]
No, I've created new keys as I already explained, and it was still throwing fits. what do you expect me to do, throw away my entire keyring and start from scratch? Why would enigmail have issues with gpg4win3 and not 2? I mean, the hung gpg processes were due to Kleopatra supplied with gpg4win3; as far as I can tell the problem is with gpg4win 3.x and neither enigmail or my setup.

**Comment by pbrunschwig** [comment]
You're perfectly right concerning the issues with GnuPG, and I'm not happy with how GnuPG performs either. But that's nothing that can be fixed within a few days or weeks, and certainly nothing that I could fix on my side. 

However, I've been working on an [OpenPGP.js](https://openpgpjs.org/) implementation for the crypto functionality over the past months. My idea is that with the next major version of Enigmail users may choose if they prefer to use GnuPG or OpenPGP.js. But it still requires quite a bit of work until that's ready for release.

**Comment by mattatobin** [comment]
Well the issue is like @wolfbeast, all current users of Enigmail are using 1.9.9 so depending on how vital their relience on it is they are going to run into the same issues and a lot of them are going to unfortunately come to me about it once this new version is pushed down the Add-ons Update Service.

In short, they are gonna be frustrated and some WILL lash out the moment that happens, against me, against you, or against both and they may stop using either the extension or client all together if it is not largely seemless and reasonably working.

That is my primary consern right now. Maybe if it was a thing when Interlink started or even a year ago then it wouldn't be so bad. Maybe for the time being, to get users accustom and transitioned it might be wise to consider setting it up on the Add-ons Site as an External and you can setup a single page for Interlink users to download and some form of 1.9.9 to the new version faq and provide an em:UpdateURL in install.rdf pointing to an update rdf until such time your js pgp module is complete.

That way in the meantime the new version and way it does things can be eased into instead of an update being shoved down the pipeline to all current 1.9.9 users resulting in "busting their stuff".

After a reasonable period of time or you get your js pgp working and it is more seemless then we can replace the external with a fully hosted version and the 1.9.9 users will get the new version from the Add-ons AUS.

Does that sound like a viable migration strategy to you, dude?

**Comment by pbrunschwig** [comment]
I'm sorry, but there is no relation between gpg4win 3.x and Enigmail 2.1.x. You can install gpg4win3, and use it with Enigmail 1.9.9, and you can install gpg4win2 and use it with Enigmail 2.1.7. The setup wizard of Enigmail 1.9.9 actually downloads the latest version gpg4win3(!).

I don't know why @wolfbeast upgraded to gp4win3 for testing Enigmail 2.1.7. I can only assume that it's because of a new feature in Enigmail 2.1.x: it checks if you're on the latest GnuPG version, and offers you to upgrade to that version. 

If you are afraid of upgrading gpg4win2 - which is a valid concern given the problems - then I'd think it would be a much better strategy to not offer any upgrades if gpg4win2 was detected. Would that address your concerns?

**Comment by mattatobin** [comment]
Perhaps. Like maybe put it behind a pref for the time being. Since this is a temporary consern cause your gpg js module with (we all hope) end the implicit dependence on having _some_ version of gpg installed.. Unless the user wants to do that.. Right?

**Comment by pbrunschwig** [comment]
> Of note: My concerns are with existing users.. New users have little to be concerned about.

Perfectly right

> Perhaps. Like maybe put the pgp version check behind a pref and off for `Interlink` for the time being. 

Yes a pref make sense - there is already such a pref, I''ll only need to make it visible.

> Since this is **ONLY a temporary concern** cause your gpg js module will (we all hope) end the implicit dependence on having _some_ version of gpg installed.. Unless the user wants to do that.. Right?

Right :-)

**Comment by mattatobin** [comment]
Well in the meantime while you are prepping.. Do read: http://developer.palemoon.org/addons/site/ .. Yeah I know it is for Pale Moon but that doesn't matter since the Add-ons Site is software shared for many UXP applications. It is just domain-based determining the application instead of path-based. (Though some changes will happen later on about getting it be either domain == application or domain == org with path == application.. Fun times ahead for that).

Anyway once you have an account you can use whatever domain you want. If for some reason your email provider doesn't like the email from Phoebus, check your spam folder, if not there tell me and I will manually activate your account.

**Comment by pbrunschwig** [comment]
OK, account creation worked. I'll upload Enigmail once I'll have completed the GnuPG update change.

**Comment by pbrunschwig** [comment]
Alright, I implemented and tested a new pref (enabled by default), which prevents upgrades from GnuPG 2.0.x to 2.2.x.

I submitted the release-addon on addons.plaemoon.org.

**Comment by mattatobin** [comment]
Understood, it is in the review process. Stand by.

**Comment by mattatobin** [comment]
And it is active and reviewed!

Thank you so much for this work and for putting the effort in as you have.

If only more long standing mozilla-style extension developers were as accommodating.

**Comment by pbrunschwig** [comment]
FYI - I announced the availability of Enigmail for Interlink on the mailing list and the support forum:
https://admin.hostpoint.ch/pipermail/enigmail-users_enigmail.net/2020-August/005694.html
