### ISSUE TITLE
Bad CSS comments for print friendly view

### ISSUE THREAD

**Issue by wolfbeast** [binaryoutcast/binoc-central#32]
Print-friendly view has a number of bad comments in CSS with `//` (not allowed in CSS, only `/* */` is)

```
Warning: Selector expected.  Ruleset ignored due to bad selector.
Source File: about:blank
Line: 376, Column: 3
Source Code:
   //body, td { font-family:Calibri, Trebuchet, Arial, sans serif; font-size:16px; line-height:22px; color:#333333; font-weight:normal;} 
Timestamp: 29/10/2018 08:37:46
Warning: Selector expected.  Ruleset ignored due to bad selector.
Source File: about:blank
Line: 377, Column: 68
Source Code:
   body, td {font-size:12px; color:#333333; font-weight:normal;}    //Save The Trees - To make templates Printer Friendly - Sindhuri 
```

**Comment by mattatobin** [comment]
Would be nice to know where that is coming from..

**Comment by wolfbeast** [comment]
Well considering the source file was "about:blank" I assumed it would be in the mailnews code somewhere.
Not very useful to mark that as source if it's content.

**Comment by mattatobin** [comment]
I beleave in circumstances like this it builds the content from a state where the the browser widget starts from about:blank after the content its self has been run through some sort of processing and sanitatization since html email isn't an html file that can simply be opened.

Could be wrong but that seems to conform with stuff I vaugely remember.

**Comment by wolfbeast** [comment]
Makes sense. In any case, sorry for the noise.

**Comment by mattatobin** [comment]
None at all it is a strange one to be sure.
