### ISSUE TITLE
Interlink 6922 xul.dll "crash" 

### ISSUE THREAD

**Issue by kn-yami** [binaryoutcast/binoc-central#60]
So Interlink crash shortly after launch. I was not interacting with the application when it crashed and I have no idea what happened. I mean I know that this is a triggered breakpoint and not an actual crash. So maybe this is some kind of a memory problem? I do not know...
##### Details provided by Windows:
```
Problem Event Name:		APPCRASH
Application Name:		interlink.exe
Application Version:		4.1.7.6922
Application Timestamp:		5c1370aa
Fault Module Name:		xul.dll
Fault Module Version:		4.1.7.6922
Fault Module Timestamp:		5c137581
Exception Code:			80000003
Exception Offset:		00000000025c26dd
OS Version:			6.1.7601.2.1.0.256.48
Locale ID:			1045
Additional Information 1:	9498
Additional Information 2:	94989334ab09b3c0f093d46df9c427d9
Additional Information 3:	ffae
Additional Information 4:	ffae1b8d6945bb03c74b139a12cb5041
```
##### Minidump:
[minidump.dmp.gz](https://github.com/binaryoutcast/binoc-central/files/2719668/minidump.dmp.gz)

(I can also provide a full core dump if needed.)

**Comment by mattatobin** [comment]
There is going to be a new version coming soon to add a few non-binary fixes to the application.

When that comes out watch for the crash.

I can't do anything with any dumps for this version because my storage drive started to fail and I had to wipe out my obj-dirs on windows to juggle enough scratch space on all my remaining drives to transfer the data.

Believe it or not, every gig counted at the time.

Though, was this with the Win32 or 64 version?

**Comment by kn-yami** [comment]
I was using the Win64 version. I will watch out the crash when the new version is released. I also hope that you have not lost any data from the failing drive.

**Comment by mattatobin** [comment]
It was starting to fail so I had to act quickly. I did get my data off it.
